on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
name: Deploy workflow
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v
    - name: Deploy
      uses: tangworkshop/action-deploy-wordpress@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        JUMPHOST_SERVER: ec2-54-80-136-241.compute-1.amazonaws.com
        WP_VERSION: 5.8.4

    - name: Cleanup
      if: ${{ always() }}
      uses: tangworkshop/action-cleanup@master
