on:
 push:
    branches:
      - master
      - develop
name: Deploy workflow
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: tangworkshop/action-deploy-wordpress@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        JUMPHOST_SERVER: 52.22.161.249
        WP_VERSION: 5.8.4

    - name: Cleanup
      if: ${{ always() }}
      uses: tangworkshop/action-cleanup@master
